#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set luci.main.lang=zh_cn
	set system.@system[0].hostname=LunaticUrey
	set system.@system[0].timezone=CST-8
	set system.@system[0].zonename=Asia/Shanghai
	set fstab.@global[0].anon_mount=1
	set wireless.@wifi-device[0].disabled=0
	set wireless.@wifi-device[1].disabled=0
	set wireless.@wifi-iface[0].wpa_disable_eapol_key_retries='1'
	set wireless.@wifi-iface[1].wpa_disable_eapol_key_retries='1'
	set wireless.radio0.country='US'
	set wireless.radio1.country='US'
	set dropbear.@dropbear[0].Interface='lan'
	set wireless.@wifi-iface[0].ssid=Lunatic_5G_$(cat /sys/class/ieee80211/phy0/macaddress | sed 's/.[0-9A-Fa-f]:.[0-9A-Fa-f]:.[0-9A-Fa-f]:\(.[0-9A-Fa-f]\):\(.[0-9A-Fa-f]\):\(.[0-9A-Fa-f]\)/\1\2\3/g' | tr :[a-z] :[A-Z])
	set wireless.@wifi-iface[1].ssid=Lunatic_2.4G_$(cat /sys/class/ieee80211/phy1/macaddress | sed 's/.[0-9A-Fa-f]:.[0-9A-Fa-f]:.[0-9A-Fa-f]:\(.[0-9A-Fa-f]\):\(.[0-9A-Fa-f]\):\(.[0-9A-Fa-f]\)/\1\2\3/g' | tr :[a-z] :[A-Z])
	set network.lan.ipaddr=192.168.7.1
	set wireless.radio0.legacy_rates='0'
	set wireless.radio1.legacy_rates='0'
	set wireless.@wifi-iface[0].disassoc_low_ack='1'
	set wireless.@wifi-iface[0].short_preamble='1'
	set wireless.@wifi-iface[1].short_preamble='1'
	set wireless.@wifi-iface[1].disassoc_low_ack='1'
	commit
EOF

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='2U4U'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt'" >> /etc/openwrt_release
sed -i '202,207d' /www/luci-static/material/js/script.js
#sed -i 's~src/gz lunaticurey_luci http://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/nand/packages/luci~src/gz lunaticurey_luci http://downloads.lede-project.org/releases/17.01-SNAPSHOT/packages/mipsel_24kc/luci~g' /etc/opkg/distfeeds.conf
#sed -i 's~option check_signature 1~#option check_signature 1~g' /etc/opkg.conf
/etc/init.d/qos_gargoyle disable
/etc/init.d/umdns stop
/etc/init.d/umdns disable
/etc/init.d/dawn stop
/etc/init.d/dawn disable
/etc/init.d/https-dns-proxy stop
/etc/init.d/https-dns-proxy disable


exit 0
